language: generic

branches:
  except:
  - staging.tmp
  - trying.tmp


matrix:
  include:
    - os: linux
      sudo: required
      services: docker
      env: myconfig=maxset image=espressomd/docker-ubuntu-20.04:06b6216c7aa3555bcf28c90734dbb84e7285c96f

script:
  - maintainer/CI/build_docker.sh
